# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OkOk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Masonry'
  pod 'Alamofire'
  pod 'SnapKit'
  pod 'SwiftLint'
  # Pods for OkOk

end
